<?php

function fl_generate_language_array_for_js_object() {

    $dev_language = FLInput::get('lang','en')
    ;    return array(
        'dev_language' => $dev_language ,
        'No' => get_custom_string_return("No") ,
        'yes' => get_custom_string_return("Yes") ,
        'message_confirm' => get_custom_string_return("Are you sure?") ,
        'content_title' => get_custom_string_return("Please enter title") ,
        'user_type' => get_custom_string_return("Please select user type") ,
        'valid_email' => get_custom_string_return("Please enter a valid email address") ,
        'password' => get_custom_string_return("Please provide a password") ,
        'confirm_password' => get_custom_string_return("Please confirm password"),
        'policy' => get_custom_string_return("Please accept our policy"),
        'email_exist' => get_custom_string_return("Email is already taken, please enter a different Email address"),
        'same_password' => get_custom_string_return("Please enter the same password as above"),
        'blank_space' => get_custom_string_return("Please don\'t use blank space"),
        'valid_password' => get_custom_string_return("Your password must be at least 6 characters long"),
        'enter_email' => get_custom_string_return("Please enter email address"),
        'promo_code_enter' => get_custom_string_return("Please enter promo code"),
        'selected_job_id' => get_custom_string_return("Please select any job") ,
        'profile_name_valid' => get_custom_string_return("Please enter your Name"),
        'phone_number_required' => get_custom_string_return("Please enter your Phone number"),
        'phone_number_digit' => get_custom_string_return("Please enter at least 9 digits"),
        'at_least_five_char' => get_custom_string_return("Please enter at least 5 characters"),
        'user_description_reason' => get_custom_string_return("Please enter your reason"),
        'user_description' => get_custom_string_return("Please enter your description"),
        'phone_number_valid' => get_custom_string_return("Please enter a valid phone number"),
        'please_enter_proper_account' => get_custom_string_return("Please enter a proper account"),
        'you_are_successfull_updated' => get_custom_string_return("Updated successfully"),
        'unauthorized_user' => get_custom_string_return("Unauthorized user"),
        'promo_code_not_available' => get_custom_string_return("This promo code is not available"),
        'promo_code_already_used' => get_custom_string_return("This promo code is already used"),
        'please_enter_email_id' => get_custom_string_return("Please enter email address"),
        'please_enter_correctemail_id' => get_custom_string_return("Please enter correct email address"),
        'please_enter_correct_conform_email_id'=> get_custom_string_return("Please enter correct email address"),
        'please_enter_your_password'=> get_custom_string_return("Please enter your password"),
        'please_enter_new_password'=> get_custom_string_return("Please enter a new password"),
        'please_enter_same_password'=> get_custom_string_return("Please enter the same password"),
        'please_enter_amount'=> get_custom_string_return("Please enter amount"),
        'please_enter_correct_amount'=> get_custom_string_return("Please enter correct amount"),
        'email_sent_successfully'=> get_custom_string_return("Email is successfully sent. Please check your email"),
        'general_file_upload_error_message'=> get_custom_string_return("General File Upload Error"),



        'linguist_user_info_YEARSATTENDED'=> get_custom_string_return("Years Attended"),
        'linguist_user_info_INSTITUTION'=> get_custom_string_return("Institution"),
        'linguist_user_info_DEGREE'=> get_custom_string_return("DEGREE"),
        'linguist_user_info_Year_recieved'=> get_custom_string_return("Year received"),
        'linguist_user_info_Recieved_from'=> get_custom_string_return("Received From"),
        'linguist_user_info_Certificate'=> get_custom_string_return("Certificate"),
        'linguist_user_info_Year_in_service'=> get_custom_string_return("Years in service"),
        'linguist_user_info_Employer'=> get_custom_string_return("Employer"),
        'linguist_user_info_Duties'=> get_custom_string_return("Duties"),
        'linguist_user_info_Language'=> get_custom_string_return("Language"),
        'linguist_user_info_Level'=> get_custom_string_return("Level"),
        'linguist_user_info_Years_of_experience'=> get_custom_string_return("Years of experience"),
        'linguist_user_info_Areas_expertise'=> get_custom_string_return("Areas/expertise"),

        'linguist_valid_attended_year'=> get_custom_string_return("Please enter years"),
        'linguist_valid_valid_attended_year'=> get_custom_string_return("Please enter a valid number"),
        'linguist_valid_attended_length'=> get_custom_string_return("Please enter no more than 10 characters"),
        'linguist_valid_institutuin'=> get_custom_string_return("Please enter institution"),
        'linguist_valid_institutuin_length'=> get_custom_string_return("Please enter no more than 50 characters in institution"),
        'linguist_valid_expertise'=> get_custom_string_return("Please enter areas of expertise"),
        'linguist_valid_expertise_length'=> get_custom_string_return("Please enter no more than 50 characters in degree"),
        'linguist_valid_received_from'=> get_custom_string_return("Please enter received from"),
        'linguist_valid_received_from_length'=> get_custom_string_return("Please enter no more than 50 characters in  received from"),
        'linguist_valid_certificate'=> get_custom_string_return("Please enter areas of certificate"),
        'linguist_valid_certificate_length'=> get_custom_string_return("Please enter no more than 50 characters in certificate"),

        'linguist_valid_year_inservice'=> get_custom_string_return("Please enter year in service"),
        'linguist_valid_valid_year_inservice'=> get_custom_string_return("Please enter a valid number in year in service"),
        'linguist_valid_year_inservice_length'=> get_custom_string_return("Please enter no more than 10 characters in year in service"),
        'linguist_valid_employer'=> get_custom_string_return("Please enter employer"),
        'linguist_valid_employer_length'=> get_custom_string_return("Please enter no more than 50 characters in employer"),
        'linguist_valid_duties'=> get_custom_string_return("Please enter duties"),
        'linguist_valid_duties_length'=> get_custom_string_return("Please enter no more than 50 characters in duties"),

        'linguist_valid_language'=> get_custom_string_return("Please enter language"),
        'linguist_valid_language_length'=> get_custom_string_return("Please enter no more than 50 characters in language"),
        'linguist_valid_year_of_experince'=> get_custom_string_return("Please Enter year of experience"),
        'linguist_valid_year_of_experince_number'=> get_custom_string_return("Please enter a valid number in year of experience"),
        'linguist_valid_year_of_experince_length'=> get_custom_string_return("Please enter no more than 10 characters in year of experience"),
        'linguist_valid_areas_expertise'=> get_custom_string_return("Please enter areas of expertise"),
        'linguist_valid_areas_expertise_length'=> get_custom_string_return("Please enter no more than 50 characters in areas expertise"),

        'full_name_enter'=> get_custom_string_return("Please enter your name"),
        'char_50_enter'=> get_custom_string_return("Please enter no more than 50 characters"),
        'char_8_enter'=> get_custom_string_return("Please enter no more than 50 characters"),
        'char_9_enter'=> get_custom_string_return("Please enter at least 9 characters"),
        'address_line_1_enter'=> get_custom_string_return("Please enter your address"),
        'town_city_enter'=> get_custom_string_return("Please enter your town city"),
        'state_enter'=> get_custom_string_return("Please enter your State"),
        'zip_code_enter'=> get_custom_string_return("Please enter correct zip code"),
        'country_enter'=> get_custom_string_return("Please enter your country"),
        'telephone_number_enter'=> get_custom_string_return("Please enter correct Phone number"),


        'note_enter'=> get_custom_string_return("Please enter value in note"),
        'amount_enter'=> get_custom_string_return("Please provide a budget amount"),
        'amount_digit_enter'=> get_custom_string_return("Please enter 0-9 digits"),
        'amount_budget'=> get_custom_string_return("Please provide an amount"),
        'amount_budget_digit_enter'=> get_custom_string_return("Please enter 0-9 digits"),
        'default_payment_enter'=> get_custom_string_return("Please select a default payment Method"),
        'select_payment_method'=> get_custom_string_return("Please select a payment Method"),
        'successfully_register'=> get_custom_string_return("You are successfully registered. Please check your email to verify the account"),
        'pre_registering'=> get_custom_string_return("Creating account. The email is being sent. Please check your email and activate the account."),
        'email_already_exist'=> get_custom_string_return("Email address is already used. Please use different email address to sign up"),
        'pleasechk_email'=> get_custom_string_return("Please check your email and activate your account"),
        'pleaseenter_upload_file'=> get_custom_string_return("Please enter or upload description/file"),
        'email_updated'=> get_custom_string_return("Update successful. Please check your email"),
        'email_exist_another'=> get_custom_string_return("Email already exists. Please use another email address"),
        'password_updated'=> get_custom_string_return("The password has been changed"),
        'field_all'=> get_custom_string_return("Please enter in all the fields"),
        'correct_digit'=> get_custom_string_return("Please enter correctly"),
        'required_field' => get_custom_string_return("This field is required"),

        'request_sent_successfully' => get_custom_string_return("Your request has been successfully sent"),
        'insufficent_balance_left' => get_custom_string_return("Insufficient balance left"),
        'enter_withdrawal_message' => get_custom_string_return("Please enter withdrawal message"),
        'you_already_withdrawal' => get_custom_string_return("Withdrawal request has been sent. You can withdraw once every three months"),
        'complete_job_before_withdrawal_request' => get_custom_string_return("You have to complete your all jobs before submitting the withdrawal request"),
        'select_rating' => get_custom_string_return("Please select rating"),
    );
}