<?php
/*
*
*
*/

if(get_option('payment_mode') == 'Live'){
	define('STRIPE_SECRET_KEY', get_option('stripe_live_secret_key'));
	define('STRIPE_PUBLISHIABLE_KEY', get_option('stripe_live_publishable_key'));
	define('PAYPAL_EMAIL', get_option('paypal_email'));
	define('PAYPAL_API_BASE_URL', 'https://www.paypal.com/us');
	define('PAYPAL_API_BASE_URL_HOST', 'www.paypal.com');

}else{
	define('STRIPE_SECRET_KEY', get_option('stripe_test_secret_key'));
	define('STRIPE_PUBLISHIABLE_KEY', get_option('stripe_test_publishable_key'));
	define('PAYPAL_EMAIL', get_option('paypal_email'));
	define('PAYPAL_API_BASE_URL', 'https://www.sandbox.paypal.com');
	define('PAYPAL_API_BASE_URL_HOST', 'www.sandbox.paypal.com');
	
}





define('ACCOUNT_ACTIVATION_TEMPLATE', 1);
define('FORGOT_PASSWORD_TEMPLATE', 2);
define('TRANSLATED_DOCUMENT_TEMPLATE', 3);
define('NEW_SERVICE_SUBMITTED_TEMPLATE', 4);
define('NEW_REVISION_REQUEST_SUBMITTED_TEMPLATE', 5);
define('HIRE_TRANSLATE_TEMPLATE', 6);
define('TIPS_BY_CUSTOMER_TEMPLATE', 7);
define('BONUS_BY_CUSTOMER_TEMPLATE', 8);
define('LINGUIST_JOB_COMPLETE_PAYMENT_RECIEVED_TEMPLATE', 9);
define('REVIEW_FEEDBACK_TEMPLATE', 10);
define('W9FORM_TEMPLATE', 11);
define('W8BEN_TEMPLATE', 12);
define('TAXFORM_TEMPLATE', 13);
define('BID_STATEMENT_TEMPLATE', 14);
define('NEW_REQUEST_EVALUTION_TEMPLATE', 15);
define('ADMIN_RECIEVE_WITHDRAWL_REQUEST_TEMPLATE', 16);
define('ACTIVATION_LINK_EMAIL_CHANGE_TEMPLATE', 17);
define('LINGUIST_REJECTED_JOB_TEMPLATE', 18);
define('JOB_ADVANCE_PAYMENT_TO_LINGUIST_TEMPLATE', 19);
define('LINGUIST_START_WORKING_TEMPLATE', 20);
define('REFILL_ACCOUNT_BY_ADMIN_TEMPLATE', 21);
define('REQUEST_EVALUTION_ACCEPTED_TEMPLATE', 22);
define('AUTOMATIC_JOB_CANCELED_NOT_SELECTED_LINGUIST_TEMPLATE', 23);
define('AUTOMATIC_JOB_REJECT_LINGUST_NOT_RESPOND_CUSTOMER_TEMPLATE', 24);
define('AUTOMATIC_JOB_REJECT_LINGUST_NOT_RESPOND_LINGUIST_TEMPLATE', 25);
define('AUTOMATIC_JOB_COMPLETED_CUSTOMER_TEMPLATE', 26);
define('AUTOMATIC_LOST_BID_DEPOSIT_TEMPLATE', 27);
define('AUTOMATIC_X_DAY_REMINDER_EMAIL_TEMPLATE', 28);
define('AUTOMATIC_Y_DAY_REMINDER_EMAIL_TEMPLATE', 29);
define('SEND_MESSAGE', 30);
define('HOURLY_NOTIFICATION_OF_NEW_AVAILABLE_JOB', 31);
define('DAILY_NOTIFICATION_OF_NEW_AVAILABLE_JOB', 32);
define('CLOSE_ACCOUNT_TEMPLATE', 33);
define('ACCOUNT_ACTIVATED_TEMPLATE', 34);
define('PLACE_NEW_ORDER', 35);
define('CANCEL_ORDER', 36);
define('RE_PLACE_ORDER', 37);
define('MEDITATION_HAS_BEEN_STARTED_CUSTOMER_EMAIL', 38);
define('RECEIVE_MESSAGE', 39);
define('REQUEST_CHANGE', 40);

define('EMAIL_TO_LINGUIST_WHEN_BID_DEPOSIT_REFUNDED', 41);
define('EMAIL_TO_USER_WHEN_REFILL_CREDIT', 42);
define('EMAIL_TO_LINGUIST_WHEN_PLACE_THE_BID', 43);
define('EMAIL_TO_CUSTOMER_APPROVE_JOB_REJECTION_BY_LINGUIST', 45);
define('EMAIL_TO_LINGUIST_JOB_REJECTION__REQUEST_BY_CUSTOMER', 46);
define('EMAIL_TO_LINGUIST_JOB_REJECTION__REQUEST_BY_ADMIN', 47);
define('EMAIL_TO_CUSTOMER_APPROVE_JOB_REJECTION_BY_ADMIN', 48);
define('MEDITATION_HAS_BEEN_STARTED_CUSTOMER_EMAIL_BY_ADMIN', 49);
define('EMAIL_TO_LINGUIST_WHEN_BID_DEPOSIT_REFUNDED_ON_APPROVE_JOB', 50);
define('EMAIL_TO_LINGUIST_WHEN_BID_DEPOSIT_REFUNDED_CUSTMOR_HIRE_ANOTHER', 51);
define('EMAIL_TO_CUSTOMER_WHEN_JOB_PARTIALLY_APPROVED', 52);
define('EMAIL_TO_LINGUIST_WHEN_JOB_PARTIALLY_APPROVED', 53);

define('AUTOMATIC_JOB_REJECTTION_APPROVE_EMAIL_TO_LINGUIST', 54);
define('AUTOMATIC_JOB_REJECTTION_APPROVE_EMAIL_TO_CUSTOMER', 55);
define('REMINDER_EMAIL_TO_ALL_SUBSCRIBER_TO_ACTIVATE_THEIR_ACCOUNT', 56);
define('REVIEW_FEEDBACK_BY_TRANSLATOR_EMAIL_TO_CUSTOMER', 57);


define('EMAIL_TEMPLATE_CONTENT_REQUEST_COMPLETION',56);
define('EMAIL_TEMPLATE_CONTENT_REQUEST_REVISION',57);
define('EMAIL_TEMPLATE_CONTENT_REQUEST_REJECTION',58);
define('EMAIL_TEMPLATE_CONTENT_PURCHASED',59);
define('EMAIL_TEMPLATE_CONTEST_REQUEST_COMPLETION',60);
define('EMAIL_TEMPLATE_CONTEST_MEDIATOR_HIRED',61);
define('EMAIL_TEMPLATE_CONTEST_REQUEST_REJECTION',62);
define('EMAIL_TEMPLATE_CONTEST_AWARDED',63);

define('EMAIL_TO_USER_WHEN_UNDO_CREDIT',64);
define('EMAIL_TO_USER_WHEN_CANNOT_CREDIT',65);





define('CASHIER_SEND_EMAIL_TO_USER', 1);
define('EVALUTION_SEND_EMAIL_TO_USER', 2);



