<?php

/*
    * current-php-code 2021-Jan-8
    * input-sanitized :
    * current-wp-template:  admin-screen  settings theme
*/

function theme_settings_panel()
{
    $b_clear_all_data = false; //set to true to allow clear data
    FreelinguistCronDeleteTempData::process_cron_controls();

    if ($b_clear_all_data && FLInput::exists('do-not-press-this-button')) {
        require_once ABSPATH.'wp-content/themes/the-translator/includes/global-functions/internal/run-once-tasks/clean-db.php';
        fl_truncate_db(false); //code-notes set param to true in the function call to output data on what it plans to do, but not actually do anything
    }
    $options = get_option('freeling_option_pages');
    ?>
    <div class="freelng-set-panle">


        <div class="panel panel-warning fl-admin-delete-test-data-panel">
            <a name="delete-test-data"> </a>
            <div class="panel-title">
                <h3>Remove Test Users</h3>
            </div>
            <div class="panel-body">
                <form method="post" action="#" name="fl-admin-delete-test-data-options-form">
                    <table>
                        <tr>
                            <th role="columnheader">
                                <label for="<?= FreelinguistCronDeleteTempData::OPTION_NAME_NUMBER_POSTS_EACH_TURN ?>">
                                    Number of Posts to Delete each Pass
                                </label>
                            </th>
                            <td style="padding-left: 2em">
                                <input type="number"
                                       id="<?= FreelinguistCronDeleteTempData::OPTION_NAME_NUMBER_POSTS_EACH_TURN ?>"
                                       name="<?= FreelinguistCronDeleteTempData::OPTION_NAME_NUMBER_POSTS_EACH_TURN ?>"
                                       value="<?= get_option(FreelinguistCronDeleteTempData::OPTION_NAME_NUMBER_POSTS_EACH_TURN,FreelinguistCronDeleteTempData::DEFAULT_NUMBER_POSTS_TO_DELETE_EACH_TURN)?>"
                                >
                            </td>
                        </tr>

                        <tr >
                            <th role="columnheader" style="padding-top: 0.5em">
                                <label for="<?= FreelinguistCronDeleteTempData::OPTION_NAME_NUMBER_USERS_EACH_TURN ?>">
                                    Number of Users to Delete each Pass
                                </label>
                            </th>
                            <td style="padding-left: 2em;padding-top: 0.5em">
                                <input type="number"
                                       id="<?= FreelinguistCronDeleteTempData::OPTION_NAME_NUMBER_USERS_EACH_TURN ?>"
                                       name="<?= FreelinguistCronDeleteTempData::OPTION_NAME_NUMBER_USERS_EACH_TURN ?>"
                                       value="<?= get_option(FreelinguistCronDeleteTempData::OPTION_NAME_NUMBER_USERS_EACH_TURN,FreelinguistCronDeleteTempData::DEFAULT_NUMBER_USERS_TO_DELETE_EACH_TURN)?>"
                                >
                            </td>
                        </tr>

                        <tr >
                            <th role="columnheader" style="padding-top: 0.5em">

                            <td style="padding-left: 2em;padding-top: 0.5em">
                                <button type="submit"  name="<?= FreelinguistCronDeleteTempData::OPTION_COMMAND?>" class="button button-primary">
                                    Update Options
                                </button>
                            </td>
                        </tr>

                    </table>
                </form>

                <form method="POST" action="#" name="fl-admin-delete-test-data-form">

                    <p> Cron job needs to be enabled to delete test users:</p>
                    <p>Linux:   */3 * * * * curl https://development:development@development.daiyan8.com/wp-cron.php?doing_wp_cron > /dev/null 2>&1</p>
                    <p>Windows:  "powershell -windowstyle hidden" "Invoke-WebRequest http://test.com/wp-cron.php?doing_wp_cron"</p>
                    <p>Tools->Scheduled Actions->search "delete" to find related jobs scheduled and error reports. . </p>

                    <p>The following button will remove all test users and posts that  are generated by using the create_random_xxx procedures in mysql db. </p>

                    <p> 1. In wp-config.php: change to the DB for cleaning;   2. Click button below; 3. Change to the original DB with large test data and rebuild ES index, as it has been deleted in step 2. </p>
                    <p> Don't change DB if deletion has not been completed! Click Pause and then change DB. Otherwise, it may crash </p>

                    <table class="form-table fl-admin-delete-test-data-cron-section">
                        <tbody>
                        <?php
                        $my_test_data = FreelinguistCronDeleteTempData::get_total_counts();
                        ?>
                        <tr class="user-rich-editing-wrap-">
                            <th role="row">
                                    <span class="fl-admin-test-count-header">
                                        Number of Test Users
                                    </span>
                            </th>
                            <td>
                                    <span class="fl-admin-test-users-count">
                                        <?= number_format($my_test_data->users, 0, '.', ',')?>
                                        Test Users
                                    </span>
                            </td>
                        </tr>

                        <tr class="user-rich-editing-wrap-">
                            <th role="row">
                                    <span class="fl-admin-test-count-header">
                                        Number of Test Posts
                                    </span>
                            </th>
                            <td>
                                        <span class="fl-admin-test-posts-count">
                                            <?= number_format($my_test_data->posts, 0, '.', ',') ?>
                                            Test Posts
                                        </span>
                            </td>
                        </tr>

                        <tr class="user-rich-editing-wrap-">


                            <td class="freelinguist-admin-hp-begining-cron-cell">

                                <button type="submit"  name="<?= FreelinguistCronDeleteTempData::START_COMMAND?>" class="button button-primary">
                                    Delete Test Data
                                </button>

                            </td>


                            <td class="freelinguist-admin-hp-middle-cron-cell">

                                <input type="submit" value="Stop Removing Test Data" name="<?= FreelinguistCronDeleteTempData::PAUSE_COMMAND?>"
                                       class="button button-primary cron-cancel"/>

                                <span class="freelinguist-explain-cron-stop">
                                        Pressing this button will stop the deleting of test data soon.
                                         After that, you can press resume to continue or start over again
                                    </span>

                                <input type="submit" value="Resume Removing Test Data"
                                       name="<?= FreelinguistCronDeleteTempData::RESUME_COMMAND?>"
                                       class="button button-primary cron-resume"/>

                                <span class="freelinguist-explain-cron-resume">
                                        Pressing this button will resume the deleting of test data cron job from where it left off.
                                    </span>

                            </td>


                            <td class="freelinguist-admin-hp-ending-cron-cell freelinguist-log-panel">

                                <div class="freelinguist-log-panel">
                                    <div class="freelinguist-log-control">
                                        <button class="button  freelinguist-show-logs freelinguist-action-popup" type="button"  data-hash="delete-test-data">
                                            Show Logs
                                        </button>
                                    </div>

                                    <div class="freelinguist-log-outer-container">
                                        <div class="freelinguist-log-area">
                                            <?php
                                            $user_short_logs = FreelinguistCronDeleteTempData::get_last_n_logs(100,false);
                                            if (empty($user_short_logs)) {
                                                $user_short_logs[] = "No logs";
                                            }
                                            foreach ($user_short_logs as $user_short_log) {
                                                ?>
                                                <span class="cron-log-line"><?= $user_short_log ?></span>
                                                <?php
                                            }

                                            ?>
                                        </div> <!-- /.freelingust-log-area -->
                                    </div> <!-- /.freelingust-log-outer-container-->
                                </div> <!-- /.freelingust-log-panel-->
                            </td>
                        </tr>
                        </tbody>
                    </table> <!-- /.fl-admin-delete-test-data-cron-section -->


                </form> <!-- /.fl-admin-delete-test-data-form -->
            </div> <!-- /.panel-body -->
            <div class="panel-footer">
                <p>Each of the users deleted will also have their ES cache data erased for them. When adding back in the same test users, need to run the cron job to build the ES cache again</p>
                <p>Logs are current as of page load, to see the more recent logs, either refresh the page again, or press the button in the log box to refresh it for you. Only the last 200 logs are kept at any time.</p>
            </div>
        </div> <!-- /.panel.fl-admin-delete-test-data-panel -->

        <div class="panel panel-danger">
            <div class="panel-title">
                <h3>Clear All Non Admin Data</h3>
            </div>
            <div class="panel-body">
                <form method="POST"
                      action="<?php echo admin_url('admin.php?page=freelinguist-admin-options'); ?>&lang=en"
                      disabled
                >
                    <div>This button will not do anything if pressed, to activate the code behind this
                        <ul style="margin-top: 0.5em; list-style: lower-greek;margin-left: 2em; padding: 1em">
                            <li>Please find $b_clear_all_data in the php of this page and set to true</li>
                            <li>Please find the button with the fl-clear-all-data class, in this page,  and remove the disabled attribute</li>
                        </ul>
                    </div>
                    <button type="submit" name="do-not-press-this-button fl-clear-all-data" class="btn btn-warning btn-lg disabled" disabled>
                        Clear Database
                    </button>
                </form>
            </div>
        </div>

        <div class="wrap">
            <h3>Set pages (this needs to be done once or twice during the site setup, don't change it if you don't know what you do)</h3>
            <?php
            if (isset($_POST['save_options'])) {
                $set_option = $_POST;
                unset($set_option['save_options']);
                update_option('freeling_option_pages', $set_option);
            }
            ?>
            <form id="setting_pannel" method="POST"
                  action="<?php echo admin_url('admin.php?page=freelinguist-admin-options'); ?>&lang=en">
                <table class="form-table">
                    <tbody>
                    <tr class="user-rich-editing-wrap">
                        <th scope="row">Login Page</th>
                        <td>
                            <select name="login_url" id="login_url" title="Login Url">
                                <option value="">Select Login Page</option>
                                <?php echo get_options_pages($options['login_url']); ?>
                            </select>
                        </td>
                    </tr>
                    <tr class="user-rich-editing-wrap">
                        <th scope="row">Registration Page</th>
                        <td>
                            <select name="registration_url" id="registration_url"  title="Registration Url">
                                <option value="">Select Registration Page</option>
                                <?php echo get_options_pages($options['registration_url']); ?>
                            </select>
                        </td>
                    </tr>
                    <tr class="user-rich-editing-wrap">
                        <th scope="row">Activation Page</th>
                        <td>
                            <select name="activation_url" id="activation_url"  title="Activation Url">
                                <option value="">Select Activation Page</option>
                                <?php echo get_options_pages($options['activation_url']); ?>
                            </select>
                        </td>
                    </tr>

                    <tr class="user-rich-editing-wrap">
                        <th scope="row">Dashboard Page</th>
                        <td>
                            <select name="dashboard_url" id="dashboard_url"  title="Dashboard URL">
                                <option value="">Select Dashboard Page</option>
                                <?php echo get_options_pages($options['dashboard_url']); ?>
                            </select>
                        </td>
                    </tr>

                    <tr class="user-rich-editing-wrap">
                        <th scope="row">My Account Page</th>
                        <td>
                            <select name="my_account_url" id="my_account_url"  title="My Account URL">
                                <option value="">Select My Account Page</option>
                                <?php echo get_options_pages($options['my_account_url']); ?>
                            </select>
                        </td>
                    </tr>

                    <tr class="user-rich-editing-wrap">
                        <th scope="row">Order Process Page</th>
                        <td>
                            <select name="order_process" id="order_process"  title="Order Process URL">
                                <option value="">Select Order Process Page</option>
                                <?php echo get_options_pages($options['order_process']); ?>
                            </select>
                        </td>
                    </tr>

                    <tr class="user-rich-editing-wrap">
                        <th scope="row">Wallet Page</th>
                        <td>
                            <select name="wallet_url" id="wallet_url"  title="Wallet URL">
                                <option value="">Select Wallet Page</option>
                                <?php echo get_options_pages($options['wallet_url']); ?>
                            </select>
                        </td>
                    </tr>

                    <tr class="user-rich-editing-wrap">
                        <th scope="row">Jobs Lisiting Page</th>
                        <td>
                            <select name="job_listing_url" id="job_listing_url"  title="Job Listing Url">
                                <option value="">Select Job Lisiting Page</option>
                                <?php echo get_options_pages($options['job_listing_url']); ?>
                            </select>
                        </td>
                    </tr>

                    <tr class="user-rich-editing-wrap">
                        <th scope="row">Single Bid Detail Page</th>
                        <td>
                            <select name="single_bid_detail_url" id="single_bid_detail_url"   title="Single Bid Details Url">
                                <option value=""> Select Single Bid Detail Page</option>
                                <?php echo get_options_pages($options['single_bid_detail_url']); ?>
                            </select>
                        </td>
                    </tr>

                    <tr class="user-rich-editing-wrap">
                        <th scope="row">User account</th>
                        <td>
                            <select name="user_account" id="user_account"   title="User Account Url">
                                <option value="">Select user account Page</option>
                                <?php echo get_options_pages($options['user_account']); ?>
                            </select>
                        </td>
                    </tr>
                    <tr class="user-rich-editing-wrap">
                        <th scope="row">Invoice</th>
                        <td>
                            <select name="invoice_page" id="invoice_page"   title="Invoice Url">
                                <option value="">Select Invoice Page</option>
                                <?php echo get_options_pages($options['invoice_page']); ?>
                            </select>
                        </td>
                    </tr>
                    <tr class="user-rich-editing-wrap">
                        <th scope="row">Forgot Password</th>
                        <td>
                            <select name="forgot_password_url" id="forgot_password_url"   title="Forgot Password Url">
                                <option value="">Select Forgot Password Page</option>
                                <?php echo get_options_pages($options['forgot_password_url']); ?>
                            </select>
                        </td>
                    </tr>
                    <tr class="user-rich-editing-wrap">
                        <th scope="row">Translator Homepage</th>
                        <td>
                            <select name="translator_homepage_url" id="translator_homepage_url"   title="Translator Homepage Url">
                                <option value="">Select Translator Homepage</option>
                                <?php echo get_options_pages($options['translator_homepage_url']); ?>
                            </select>
                        </td>
                    </tr>
                    <tr class="user-rich-editing-wrap">
                        <th scope="row">Terms & conditions</th>
                        <td>
                            <select name="terms_conditions_url" id="terms_conditions_url"   title="Terms and Conditions Url">
                                <option value="">Select Terms & conditions Page</option>
                                <?php echo get_options_pages($options['terms_conditions_url']); ?>
                            </select>
                        </td>
                    </tr>
                    <tr class="user-rich-editing-wrap">
                        <th scope="row">Setting</th>
                        <td>
                            <select name="setting_page_url" id="setting_page_url"   title="Setting Page Url">
                                <option value="">Select Setting Page</option>
                                <?php echo get_options_pages($options['setting_page_url']); ?>
                            </select>
                        </td>
                    </tr>
                    <tr class="user-rich-editing-wrap">
                        <th scope="row">Linguist Support</th>
                        <td>
                            <select name="linguist_support_page_url" id="linguist_support_page_url"   title="Linguist Support Page Url">
                                <option value="">Select Linguist Support page</option>
                                <?php echo get_options_pages($options['linguist_support_page_url']); ?>
                            </select>
                        </td>
                    </tr>
                    <tr class="user-rich-editing-wrap">
                        <th scope="row">Customer Support</th>
                        <td>
                            <select name="customer_support_page_url" id="customer_support_page_url"   title="Customer Support Page Url">
                                <option value="">Select Customer Support page</option>
                                <?php echo get_options_pages($options['customer_support_page_url']); ?>
                            </select>
                        </td>
                    </tr>
                    <tr class="user-rich-editing-wrap">
                        <th scope="row">Content Detail</th>
                        <td>
                            <select name="content_detail_url" id="content_detail_url"   title="Content Detail Page Url">
                                <option value="">Select content detail</option>
                                <?php echo get_options_pages($options['content_detail_url']); ?>
                            </select>
                        </td>
                    </tr>
                    <tr class="user-rich-editing-wrap">
                        <th scope="row">Linguist Content</th>
                        <td>
                            <select name="linguist_content_url" id="linguist_content_url"   title="Linguist Content Url">
                                <option value="">Select Linguist content</option>
                                <?php echo get_options_pages($options['linguist_content_url']); ?>
                            </select>
                        </td>
                    </tr>
                    <tr class="user-rich-editing-wrap">
                        <th scope="row">Linguist Add Content</th>
                        <td>
                            <select name="linguist_add_content_url" id="linguist_add_content_url"   title="Linguist Add Content Url">
                                <option value="">Select Linguist add content</option>
                                <?php echo get_options_pages($options['linguist_add_content_url']); ?>
                            </select>
                        </td>
                    </tr>
                    <tr class="user-rich-editing-wrap">
                        <th scope="row">How It Works</th>
                        <td>
                            <select name="how_it_works" id="how_it_works"   title=" How it works Url">
                                <option value="">Select how it works</option>
                                <?php echo get_options_pages($options['how_it_works']); ?>
                            </select>
                        </td>
                    </tr>
                    <tr class="user-rich-editing-wrap">
                        <th scope="row"><input type="submit" name="save_options"></th>
                        <td></td>
                    </tr>
                    </tbody>
                </table>

            </form>
        </div>



    </div>
<?php }

function get_options_pages($selected = null){
    $pages = get_pages();
    $option = "";
    foreach ($pages as $row) {
        $is_selected = ($selected == $row->ID) ? 'selected' : '';
        $option .= '<option value="'.$row->ID.'" '.$is_selected.'>'.$row->post_title.'</option>';
    }
    return $option;
}