<div class="container">
    <p style="text-align: justify;">This Nondisclosure Agreement (this “Agreement”), effective upon the date of electronic acceptance (“Effective Date”), is entered by and between PeerOK (also referred to as “Company”) and the Freelancer who is performing Freelancer services under the Terms and Conditions, Privacy Policy and associated material of the Company and its website, PeerOK.com. And, each is herein referred to also generically and individually as a “Party”, or collectively as the “Parties”. In consideration of the covenants and conditions contained herein, and for other consideration set forth in the Terms and Conditions and other materials, the parties agree as follows:</p>
    <p style="text-align: justify;">Introduction:</p>
    <p style="text-align: justify;">For the parties hereto to conduct a business relationship with each other, and with the “Client”, who is the consumer who is interested in purchasing translation and other services from the Freelancer, the Company and the Freelancer, in performing the services promised under the PeerOK platform, may receive confidential information from the Client, directly or indirectly. In addition, the Company may possibly disclose confidential or proprietary information regarding itself to the Freelancer, and the Freelancer may possibly disclose confidential or proprietary information regarding itself to the Company.</p>
    <p style="text-align: justify;">Confidential Information:</p>
    <p style="text-align: justify;">The Confidential Information of either the Company, the Freelancer or the Client, may include but is not limited to business activities and plans, financial results and projections, costs and prices, software, hardware configurations, financial documents, inventions, processes, designs, prototypes, samples, data sets, drawings, customers, markets, equipment, product plans, customers, suppliers, employees, consultants, technologies, technical and business strategies, the Company’s plant and equipment, trademarks, patents and patent applications, and trade secrets (the "Confidential Information"). Confidential Information also includes draft contracts and executed contracts, work papers, and related documents or exhibits exchanged by the parties, including possibly extensive information and work papers provided by the Client, as aforesaid.</p>
    <p style="text-align: justify;">Nondisclosure / Noncircumvent Provisions:</p>
    <p style="text-align: justify;">1. The Confidential Information in this agreement pertains to that of the Company, the Freelancer and the Client.<br />
        2. Nothing shall prevent the Company from using the data, information, documentation and any things of any kind provided to it by Freelancer or by the Client, whether confidential or not, that are required to perform its functions and authority defined and described in the Terms and Conditions and associated materials making up an agreement already entered by the Freelancer and the Company and included above as part of this comprehensive Terms and Conditions Agreement. This authority imparted to PeerOK is meant to be a broad and encompassing exclusion of the duty of confidentiality on the part of the Company wherever there is any possible or potential need for the Company to disclose such information, which includes but is not limited to, the legal compulsion exclusion described further below.<br />
        3. Subject to the broad exclusions stated in Paragraph 2, that deal with the possible necessity of the Company to disclose confidential information of the Freelancer and the Client, each party shall use its reasonable best efforts to keep the other's Confidential Information secret. Subject to the exclusions in Paragraph 2, each party shall use at least the same degree of care to avoid unauthorized disclosure or use of the other's Confidential Information as it employs with respect to its own Confidential Information of like importance.<br />
        4. The Freelancer also agrees to protect the Confidential Information of the consumer, i.e., the Client, who shall provide work documents to the Freelancer which may contain sensitive confidential information regarding the Client’s activities or business operations, as above defined, or even personal confidential information that is highly private and must remain undisclosed to any persons or entities beyond those described herein.<br />
        5. Neither party has any obligation with respect to any Confidential Information which (a) is or becomes publicly known without a breach of this Agreement by either party or is known prior to the date hereof; (b) is disclosed to it by a third person who is not required to maintain its confidentiality; or (c) is approved for release by the other party in writing. The party claiming any of the above exceptions has the burden of proving its applicability.<br />
        5. Each party may disclose Confidential Information to its own officers, directors, employees and advisors who reasonably need to know it ("Designees"). Each party shall take appropriate action (by instructions, agreement, or otherwise) with its Designees to satisfy its obligations under this Agreement. Each party shall be responsible to the other for any violation of this Agreement by its own Designees. Neither party may disclose Confidential Information to any other persons or entities, except as is necessary and allowed by Paragraph 2, and without also first obtaining from each such person an agreement substantially identical to this Agreement in form (a "Companion Agreement").<br />
        6. Neither party may use the other's Confidential Information for competing with the other or for any purpose not in furtherance of the business relationship between them. The Freelancer shall not use the Client’s Confidential Information for competing with the Client or for any purpose not in furtherance of the business relationship between them.<br />
        7. Subject to the broad exclusions granted to the company, the parties also agree not to attempt to circumvent this agreement. That in the event of circumvention of this agreement by either party, directly or indirectly, the circumvented party shall be entitled to collect damages flowing therefrom, in addition to a legal monetary penalty equal to maximum service it should realize from such a transaction plus all expenses, including but not limited to all legal costs and expenses incurred to recover the lost revenue.<br />
        8. Each party's Confidential Information shall remain its own property. Upon the termination of the business relationship or upon request, whichever is sooner, each party shall return all of the other's Confidential Information, or destroy it and provide the other party with written certification of such destruction. The Freelancer shall destroy or return all of the Client’s work instructions and work papers, confidential or not, per the dictates set forth in further detail in the Terms and Conditions of PeerOK and PeerOK.com with respect to its web site platform and any app(s).<br />
        9. If either party becomes legally obligated, or receives a subpoena or other legal demand, to disclose any of the other party's Confidential Information, the party subject to the obligation shall notify the other party in writing immediately, shall cooperate with the other party in seeking a protective order or other appropriate remedy, and shall use its reasonable best efforts to protect the confidential and proprietary status of any disclosed Confidential Information.<br />
        10. Each party agrees that in the event of a breach or threatened breach by either party, including its officers, agents, directors, or employees, of the provisions of this Agreement, the nonbreaching party may have no adequate remedy in money damages and, accordingly, shall be entitled to an injunction against such breach, in addition to any other legal or equitable remedies available to it.<br />
        11. This Agreement is governed by the laws of Texas without regard to its rules on conflicts law, and both parties consent to the venue and jurisdiction of its courts. Neither party may assign its rights or obligations under this Agreement, except that the Company may assign this agreement to its successors in the event of a merger, consolidation or other transformation of the business entity of the company. No modification of this Agreement shall be effective unless in writing and signed by both parties. No waiver of any provision of this Agreement shall be effective unless signed by the waiving party. This Agreement (which includes by reference the Terms and Conditions, Privacy Policy, Administrative Provisions, and all other materials appearing in the documents and provisions above) is the entire agreement between the parties on nondisclosure of confidential information and supersedes all prior representations and agreements between the parties on that subject.<br />
        12. You agree that you have read and understand this agreement and agree with your responsibilities hereunder.<br />
        13. By going ahead and using the PeerOK and PeerOK.com platform(s) or its app(s), you agree to be bound by this nondisclosure, noncircumvent agreement. You acknowledge that you understand that you cannot register as a Member and use the site without being bound to this agreement.</p>
</div>