<div class="container">The parties, being PeerOK, PeerOK.com, and wenren8.com (sometimes referred to as the Company), and the Freelancer, agree that the procedure for the assignment and performance of job services shall be as follows:<br />
    1. PeerOK.com shall negotiate and contract with a Freelancer for the completion of a job.<br />
    2. PeerOK.com will evaluate the technical qualifications of a Freelancer based on the material uploaded by the Freelancer and will assign corresponding technical levels. The Freelancer may rate higher for some services based on the background and qualifications presented and lower for other types of services. The Freelancer may request a reconsideration, but acknowledge that any such change in status shall be at the sole and absolute discretion of the Company.<br />
    3. The parties recognize and agree that PeerOK is solely responsible for setting the technical levels but that it shall be doing this based solely on the information, documentation, referrals and representations provided or made by the Freelancer, and any inaccuracies or errors in the information provided by Freelancer shall not be the responsibility of PeerOK, and any damages created to anyone thereby shall be solely the responsibility of the Freelancer, as per the disclaimers, waivers, and other legal representations by PeerOK made in the Terms and Conditions, which are incorporated herein and made a part hereof as if appearing here at length..<br />
    4. The payment rate and percentage of bonus and tip payment for the Freelancer is solely based on the technical levels, which is solely determined by PeerOK.com.<br />
    5. Upon the assignment of the technical levels from PeerOK.com, the Freelancer agrees to accept the payment rate and percentage of bonus and tip payment for performing corresponding types of freelance Freelancer services on the PeerOK platform. Bonus and tip payments are up to the Client and are not regulated by PeerOK.<br />
    6. The Freelancer may find his technical levels and payment rate on his profile page. The Freelancer may also contact PeerOK.com for the information of his payment rate and percentage of bonus and tip payment. The information of technical levels, and the related payment rate and percentage of bonus and tip payment will also be included in the evaluation email sent from PeerOK.com to the Freelancer after the Freelancer has requested evaluation. Freelancer's acceptance of such offer qualifies the Freelancer to place bids and compete for job services in accordance with his skill levels on PeerOK.com.<br />
    7. As a Freelancer, you are always independent of PeerOK.com and shall not at any time be considered an employee of PeerOK.com. Accordingly, Freelancers shall not be entitled to benefits offered to PeerOK’s employees and shall not be administratively carried on the books of the company as employees. The parties recognize that the work done by the Freelancer is independent and that the Freelancer calls her own hours, pace of work, type of work selected. In addition, PeerOK does not supervise the work performed nor provide training for such work.<br />
    8. The Freelancer agrees to be solely responsible for all taxes, license fees, and business expenses it incurs in the performance of all services, marketing and advertising hereunder or elsewhere. Both the Client and Freelancer agree to indemnify PeerOK.com for any taxes or penalties that may at any time be imposed on PeerOK.com by the purchase and sale of services between them on this Site.Freelancer Shall Provide a Satisfactory Level of Competence and Work Quality:9. PeerOK.com evaluates each Freelancer by reviewing materials (i.e. resume, writing sample, education, experience, awards, certificates, etc.) submitted by a Freelancer, and PeerOK will use that material and any other documentation to assess the Freelancer's education, background, skill and expertise, and to assign technical levels and thus service payment rate and percentage of bonus and tip payments to that Freelancer.<br />
    10. When a Client submits a job to PeerOK.com, PeerOK.com posts the job so that all Freelancers can view public information of the job. The Freelancer may place a bid if the Freelancer is interested in the job and confident of having the requisite professional skills to complete the job successfully. By placing a bid on a job, the Freelancer agrees to pay a bid security deposit to PeerOK.com, the amount of which is solely determined by PeerOK.com and made available on the site.<br />
    11. The bid security deposit will be fully refunded to the Freelancer if one of the following happens:<br />
    a). the job is started by another Freelancer selected by the Client;<br />
    b). the job is cancelled before the job is started;<br />
    c). the Freelancer is selected for the job, starts the job, and successfully completes the job so that the job is approved completed by the Client.<br />
    12. The Freelancer agrees to bid on jobs only after careful consideration regarding the Freelancer's background, skill, expertise, past performance, and style so that the Freelancer is confident of having the requisite professional skills to complete the job successfully. The Freelancer releases, and will save and hold harmless, PeerOK, its successors, assigns, owners, employees and all others from any demand or claim for losses or damages made by a Client who claims that the Freelancer was not skilled enough to perform the job. Both Client and Freelancer hereby recognize and affirm that they are aware that PeerOK cannot and does not review the qualifications of the Freelancer to perform any job that is negotiated and entered from the PeerOK platform.<br />
    13. The Freelancer and Client may and are encouraged to discuss the details and skills required prior to the parties determining whether they are a fit for the services requested. The parties may ask each other questions, and this is the opportune time for the Freelancer to determine whether the services are a match for his or her skillset.


    <p style="text-align: justify;">Deadlines for Freelancers to Deliver Content</p>
    <p>14. Upon starting service of a job by clicking “START SERVICE”, the Freelancer enters contract with the Client and the Freelancer agrees that the service files will be uploaded and submitted on or before the stated delivery date given in the order.<br />
        15. All Members shall honor the confidential nature of the work performed. Freelancer shall not repeat or describe to others the nature or details of the job performed for any Client. A violation of the duty of strict compliance with confidentiality is grounds for termination of the Freelancer from the service, as determined by PeerOK in its sole discretion.<br />
        16. In addition, for jobs that require the downloading of content, you must agree to delete all original content (“Client Content”) within 30 days. Client Content is the property of the customer; by possessing it past 30 days, the Freelancer is breaching client confidential protocols and is subject to penalty and/or forfeiture of service fees.<br />
        17. Service contracts may not be communicated to third parties for obtaining more work or for other ulterior motives. Service content prepared for a Client cannot be shared with third persons.</p>
    <p>Quality Translations are the Standard Required of Freelancer</p>
    <p>18. As a Freelancer, you agree to consistently meet the quality standards requested by the Client. You agree to provide as many drafts as reasonably requested to satisfy the Client in difficult, lengthy or complex assignments, until the Client approves the completion of the work. if your rating is below three for three consecutive times, PeerOK reserves the right to lower your technical level by one. It is recognized, however, that occasionally a Client may make unrealistic or unclear demands that cannot reasonably be satisfied. It is in the Freelancer’s best interest to contact PeerOK in that event as soon as possible so a mediation process may take place to try and complete the project to everyone’s satisfaction. PeerOK shall be the sole and exclusive judge of whether the Client is being unreasonable or whether the Freelancer is not working up to his or her skill level.<br />
        19. Freelancer should only upload delivery content using the UPLOAD SERVICE FILE function of the site. Do not place delivery content in the comments section of a job or in any third-party communications tool. A Client could take the delivered content and reject your job, meaning you would not get paid for the work you have done. If you experience issues when submitting your delivered content, please report it to us immediately, and we will resolve the problem promptly.<br />
        20. Freelancer shall answer comments speedily and professionally. Please carefully read the comments and queries from customers and answer them promptly, clearly, and in a friendly manner. Do not use abusive or profane language or give excuses or personal background information to customers. Try to resolve disputes in a friendly and efficient way. Being defensive is not the way to build up a lucrative body of paying customers.<br />
        21. Freelancer understands the importance of meeting deadlines and will always strive to do so. Where an unavoidable and just reason arises for a delay, contact us immediately to get an extension or otherwise resolve the problem.<br />
        22. When considering a job, make sure you have the time, knowledge and skills to complete it by the expected deadline. Do not start a job if you cannot finish it on time. After receiving revision requests, you agree to respond within 24 hours and submit the revised service content.<br />
        23. All disputes between Freelancer and Client, including with respect to quality, duration, timelines and any other issue relative to the work and payment of Freelancer, shall be reported to PeerOK. The procedure set forth in the main body of the Terms and Conditions, at Section 5.63 therein, defines the way in which disputes will be processed, handled and resolved. You hereby agree that PeerOK shall have the sole and absolute right to decide the resolution of all such disputes, after PeerOK has reviewed all facts that each party wants to submit on the issue(s). You hereby agree to be bound by the decision rendered by PeerOK, without appeal or further claims.<br />
        24. The parties recognize and hereby agree that the Nondisclosure agreement, the Terms and Conditions, Privacy Policy, Administrative Provisions, and all other sections and provisions appearing above or appearing on the website or in app(s) are incorporated herein and made a part hereof as though set forth here at length.<br />
        25. By going forward and becoming a Member of the PeerOK platform, you are agreeing to be bound by these provisions, and if you not agree you acknowledge and affirm that you will not register as a Member and You will cease to access this website or its app(s).</p>
</div>