INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (4, 5, '_edit_last', '621');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (5, 5, '_edit_lock', '1516669451:621');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (6, 5, '_wp_page_template', 'templates/registration-tpl.php');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (183283, 5, '_aioseop_description', 'PeerOK.com is a leading marketplace for a comprehensive range of linguistic and textual services. 100% satisfaction guaranteed. ');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (183284, 5, '_aioseop_title', 'Registration');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (7, 7, '_edit_lock', '1616460251:3534');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (8, 7, '_edit_last', '621');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (9, 7, '_wp_page_template', 'templates/acc-active-tpl.php');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (182491, 7, '_aioseop_description', 'Activate your profile at FreeLinguist');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (182492, 7, '_aioseop_title', 'Activation');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (10, 9, '_edit_lock', '1566991753:3534');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (11, 9, '_edit_last', '621');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (12, 9, '_wp_page_template', 'templates/login-tpl.php');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (183474, 9, '_aioseop_description', 'PeerOK.com is a leading marketplace for a comprehensive range of linguistic and textual services. 100% satisfaction guaranteed.');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (183475, 9, '_aioseop_title', 'Freelance');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (13, 13, '_edit_last', '621');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (14, 13, '_wp_page_template', 'templates/dashboard-tpl.php');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (15, 13, '_edit_lock', '1565699147:3534');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (183842, 13, '_aioseop_description', 'Get quality translation, editing, and writing content at 15% price of traditional service providers. Read free content and buy quality content, news report, articles, essays.');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (183843, 13, '_aioseop_title', 'Content and service');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (17, 22, '_edit_last', '621');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (18, 22, '_wp_page_template', 'templates/order-process-tpl.php');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (19, 22, '_edit_lock', '1528799363:1');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (788, 369, '_edit_lock', '1516672232:621');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (789, 369, '_edit_last', '621');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (790, 369, '_wp_page_template', 'templates/jobs-tpl.php');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (183596, 369, '_aioseop_description', 'PeerOK.com is a leading marketplace for a comprehensive range of linguistic and textual services. 100% satisfaction guaranteed.');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (183597, 369, '_aioseop_title', 'Post projects');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (791, 371, '_edit_lock', '1516672152:621');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (792, 371, '_edit_last', '621');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (793, 371, '_wp_page_template', 'templates/account-tpl.php');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (907, 406, '_edit_lock', '1516663015:621');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (908, 406, '_edit_last', '621');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (909, 406, '_wp_page_template', 'templates/wallet-tpl.php');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (182755, 406, '_aioseop_description', 'Make unlimited earnings at PeerOK. Provide professional language services and assist the language needs of our customers. ');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (182756, 406, '_aioseop_title', 'Earn money');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (1151, 465, '_edit_lock', '1614543288:3534');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (1152, 465, '_edit_last', '3534');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (1153, 465, '_wp_page_template', 'templates/translator-homepage-tpl.php');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (182987, 465, '_aioseop_description', 'Provide freelance language service to our thousands of customers worldwide. Highest payment rate guaranteed. Make unlimited earnings every day!');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (182988, 465, '_aioseop_title', 'Highest payment rate');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (1865, 572, '_edit_lock', '1541676654:621');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (1866, 572, '_edit_last', '621');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (1867, 572, '_wp_page_template', 'templates/author-user-info.php');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (182871, 572, '_aioseop_description', 'Keep an attractive account at PeerOK. But any textual content and buy any language services. 100% satisfaction guaranteed, or money back.  ');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (182872, 572, '_aioseop_title', 'Account');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (2505, 681, '_edit_last', '621');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (2506, 681, '_wp_page_template', 'templates/forgot-password.php');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (2507, 681, '_edit_lock', '1516672672:621');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (3204, 828, '_edit_lock', '1516663578:621');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (3205, 828, '_edit_last', '621');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (3206, 828, '_wp_page_template', 'templates/setting-tpl.php');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (183167, 828, '_aioseop_description', 'Professional language services, buy textual content, read free content! Enjoy services provided by thousands of linguists worldwide. ');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (183168, 828, '_aioseop_title', 'Setting');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (3274, 835, '_edit_lock', '1516663371:621');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (3275, 835, '_edit_last', '621');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (3276, 835, '_wp_page_template', 'templates/linguist-support-tpl.php');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (182991, 835, '_aioseop_description', 'We are here 24/7 to help you! You can contact us anytime. We are available anytime to give good support to provide quality freelance services to our customers. ');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (182992, 835, '_aioseop_title', 'Support');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (17891, 3002, '_edit_lock', '1536555476:1');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (17892, 3002, '_edit_last', '1');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (17893, 3002, '_wp_page_template', 'templates/home-tpl.php');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (18976, 3002, 'content_editor', '<h2>How it Works</h2>
only three steps');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (18977, 3002, '_content_editor', 'field_57cff485dbbde');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (18978, 3002, 'process_0_add_title', 'Post Project');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (18979, 3002, '_process_0_add_title', 'field_57cff4c7dbbe0');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (18980, 3002, 'process_0_short_description', 'Upload files <br/> Submit order<br/>(Cancellable) ');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (18981, 3002, '_process_0_short_description', 'field_57cff4ffdbbe1');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (18982, 3002, 'process', '3');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (18983, 3002, '_process', 'field_57cff4afdbbdf');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (18984, 3002, 'ct_editor', '<h2>Get Your Content Serviced by Professionals</h2>
We connect more than 20,000 customers with Native Linguists');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (18985, 3002, '_ct_editor', 'field_57cff90d9af5a');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (18986, 3002, 'service_0_icon', '3169');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (18987, 3002, '_service_0_icon', 'field_57cff9569af5c');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (18988, 3002, 'service_0_description', '<strong>Maximum Value</strong>

minimizes your cost with prices starting at just $0.02/word.');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (18989, 3002, '_service_0_description', 'field_57cff9a89af5d');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (18990, 3002, 'service', '3');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (18991, 3002, '_service', 'field_57cff9219af5b');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (19016, 3002, 'process_1_add_title', 'Select Translator/Editor<br/>/Writer');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (19017, 3002, '_process_1_add_title', 'field_57cff4c7dbbe0');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (19018, 3002, 'process_1_short_description', 'Linguists place bids <br/> Choose favorite <br/> linguist');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (19019, 3002, '_process_1_short_description', 'field_57cff4ffdbbe1');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (19020, 3002, 'process_2_add_title', 'Receive <br/> Content');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (19021, 3002, '_process_2_add_title', 'field_57cff4c7dbbe0');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (19022, 3002, 'process_2_short_description', 'Download services <br/>Revise until 100% satisfied');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (19023, 3002, '_process_2_short_description', 'field_57cff4ffdbbe1');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (19080, 3002, 'service_1_icon', '3221');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (19081, 3002, '_service_1_icon', 'field_57cff9569af5c');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (19082, 3002, 'service_1_description', '<strong>Cutting-edge tech</strong>

automates and simplifies the linguistic process.');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (19083, 3002, '_service_1_description', 'field_57cff9a89af5d');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (19084, 3002, 'service_2_icon', '3222');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (19085, 3002, '_service_2_icon', 'field_57cff9569af5c');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (19086, 3002, 'service_2_description', '<strong>Instant Quote</strong>

starts your services
RIGHT NOW!');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (19087, 3002, '_service_2_description', 'field_57cff9a89af5d');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (41547, 3002, 'availabe_process', 'We are available 24x7');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (41548, 3002, '_availabe_process', 'field_585bc4ad166b0');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (41549, 3002, 'availabe_content', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum lacinia massa, eget  rutrum est gravida sit amet. Fusce hendrerit at lacus eu ullamcorper');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (41550, 3002, '_availabe_content', 'field_585bc4df166b1');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (41694, 3002, 'available_process', 'We are available 24/7');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (41695, 3002, '_available_process', 'field_585bc4ad166b0');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (41696, 3002, 'available_content', 'Our global network of linguists will deliver in a timely manner no matter when you need it');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (41697, 3002, '_available_content', 'field_585bc4df166b1');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (185554, 24708, '_edit_lock', '1614296770:3534');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (185555, 24708, '_edit_last', '1');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (185556, 24708, '_wp_page_template', 'templates/HTMLPAGE-how-it-work-tpl.php');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (185557, 24710, '_edit_lock', '1555415001:1');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (185558, 24710, '_edit_last', '1');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (185559, 24710, '_wp_page_template', 'templates/linguists-add-content-tpl.php');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (185562, 24712, '_edit_lock', '1523604211:1');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (185563, 24712, '_edit_last', '1');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (185564, 24712, '_wp_page_template', 'templates/linguists-content-tpl.php');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (185699, 24776, '_edit_lock', '1616460588:3534');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (185700, 24776, '_edit_last', '1');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (185701, 24776, '_wp_page_template', 'templates/content-detail-tpl.php');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (185721, 24789, '_edit_lock', '1537940464:1');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (185722, 24789, '_edit_last', '1');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (185723, 24789, '_wp_page_template', 'templates/HTMLPAGE-search-page.php');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (187794, 25319, '_edit_lock', '1527169608:1');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (187795, 25319, '_edit_last', '1');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (187796, 25319, '_wp_page_template', 'templates/post-contest-tpl.php');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (195287, 27436, '_edit_lock', '1547448173:1');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (195288, 27436, '_edit_last', '1');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (195289, 27436, '_wp_page_template', 'templates/HTMLPAGE-fav-page.php');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (225140, 29110, '_edit_lock', '1616462508:3534');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (225141, 29110, '_edit_last', '3534');
INSERT INTO peerok_small.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (225142, 29110, '_wp_page_template', 'templates/my-content.php');